//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvDbDotNet.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TvDbDotNet.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Languages&gt;
        ///  &lt;Language&gt;
        ///    &lt;name&gt;Dansk&lt;/name&gt;
        ///    &lt;abbreviation&gt;da&lt;/abbreviation&gt;
        ///    &lt;id&gt;10&lt;/id&gt;
        ///  &lt;/Language&gt;
        ///  &lt;Language&gt;
        ///    &lt;name&gt;Suomeksi&lt;/name&gt;
        ///    &lt;abbreviation&gt;fi&lt;/abbreviation&gt;
        ///    &lt;id&gt;11&lt;/id&gt;
        ///  &lt;/Language&gt;
        ///  &lt;Language&gt;
        ///    &lt;name&gt;Nederlands&lt;/name&gt;
        ///    &lt;abbreviation&gt;nl&lt;/abbreviation&gt;
        ///    &lt;id&gt;13&lt;/id&gt;
        ///  &lt;/Language&gt;
        ///  &lt;Language&gt;
        ///    &lt;name&gt;Deutsch&lt;/name&gt;
        ///    &lt;abbreviation&gt;de&lt;/abbreviation&gt;
        ///    &lt;id&gt;14&lt;/id&gt;
        ///  &lt;/Language&gt;
        ///  &lt;Language&gt;
        ///    &lt;name&gt;Italiano&lt;/name&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Mirrors&gt;
        ///    &lt;Mirror&gt;
        ///        &lt;id&gt;4&lt;/id&gt;
        ///        &lt;mirrorpath&gt;http://thetvdb.com&lt;/mirrorpath&gt;
        ///        &lt;typemask&gt;5&lt;/typemask&gt;
        ///    &lt;/Mirror&gt;
        ///&lt;/Mirrors&gt;.
        /// </summary>
        internal static string mirrors {
            get {
                return ResourceManager.GetString("mirrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Data&gt;&lt;Series&gt;
        ///  &lt;id&gt;72449&lt;/id&gt;
        ///  &lt;Actors&gt;|Richard Dean Anderson|Amanda Tapping|Christopher Judge|Gary Jones|Teryl Rothery|Claudia Black|Ben Browder|Corin Nemec|Michael Shanks|Don S. Davis|Beau Bridges|&lt;/Actors&gt;
        ///  &lt;Airs_DayOfWeek&gt;Friday&lt;/Airs_DayOfWeek&gt;
        ///  &lt;Airs_Time&gt;8:00 PM&lt;/Airs_Time&gt;
        ///  &lt;ContentRating&gt;TV-PG&lt;/ContentRating&gt;
        ///  &lt;FirstAired&gt;1997-07-01&lt;/FirstAired&gt;
        ///  &lt;Genre&gt;|Action and Adventure|Science-Fiction|&lt;/Genre&gt;
        ///  &lt;IMDB_ID&gt;tt0118480&lt;/IMDB_ID&gt;
        ///  &lt;Language&gt;en&lt;/Langu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///    &lt;Series&gt;
        ///        &lt;seriesid&gt;70851&lt;/seriesid&gt;
        ///        &lt;language&gt;en&lt;/language&gt;
        ///        &lt;SeriesName&gt;Stargate Atlantis&lt;/SeriesName&gt;
        ///        &lt;banner&gt;graphical/70851-g9.jpg&lt;/banner&gt;
        ///        &lt;Overview&gt;Stargate Atlantis, often abbreviated as SGA, is a Canadian-American military science fiction television series and part of MGM&apos;s Stargate franchise. The show was created by Brad Wright and Robert C. Cooper, as a spin-off series of Stargate SG-1 created by Wrigh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seriesSearchResults {
            get {
                return ResourceManager.GetString("seriesSearchResults", resourceCulture);
            }
        }
    }
}
